name: Atualiza README com data

on:
  schedule:
    - cron: "0 3 * * *"  # Todos os dias às 03:00 UTC (00:00 no Brasil)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Atualizar data no README
        run: |
          data=$(date +"%d/%m/%Y")
          sed -i "s/{{DATA}}/${data}/g" README.md

      - name: Fazer commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando README com data ${data}" || echo "Nada para commitar"
          git push
